//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parking
    {
        public int Id { get; set; }
        public int BayId { get; set; }
        public double lat { get; set; }
        public double lon { get; set; }
        public string area { get; set; }
        public string location { get; set; }
        public string des_dis_ext { get; set; }
    }
}
