//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicToilet
    {
        public int Id { get; set; }
        public Nullable<decimal> lat { get; set; }
        public Nullable<decimal> lon { get; set; }
        public string name { get; set; }
        public string female { get; set; }
        public string male { get; set; }
        public string wheelchair { get; set; }
        public string @operator { get; set; }
        public string baby_facil { get; set; }
        public string location { get; set; }
        public string Address { get; set; }
        public Nullable<int> Postcode { get; set; }
    }
}
