//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainStation
    {
        public int Id { get; set; }
        public string station { get; set; }
        public string location { get; set; }
        public string passenger_information_display_system { get; set; }
        public string hearing_aid { get; set; }
        public string lift { get; set; }
    }
}
